//NextJS
import Head from "next/head";

//Components
import Hero from "@/components/Hero";

// Translation
import { useTranslation } from '@/hooks/useTranslation';

export default function TermsOfUse() {
  const { t } = useTranslation();
  
  return (
    <>
      <Head>
        <title>{t('terms.title')} - Waveful</title>
      </Head>
      <main>
        <section className="mx-auto max-w-[840px] mt-24 px-5 py-14">
          <h1 className="text-3xl font-bold mb-4">{t('terms.title')}</h1>
          <h2 className="text-xl font-bold mt-6 mb-2">{t('terms.intro')}</h2>
          <p className="mb-4">{t('terms.welcome')}</p>
          <h3 className="text-lg font-bold mt-6 mb-2">{t('terms.missionTitle')}</h3>
          <p className="mb-4">{t('terms.mission')}</p>
          <p className="mb-4">{t('terms.rules')}</p>
          <p className="mb-6">{t('terms.creatorNote')}</p>
          <p className="mb-6" dangerouslySetInnerHTML={{
            __html: t('terms.contact').replace('${email}', '<a href="mailto:support@waveful.app" class="underline">support@waveful.app</a>')
          }} />

        <h2 className="text-xl font-bold mt-6 mb-2">Recitals and Definitions</h2>
        These terms and conditions of use (the "Conditions" or the "Agreement") govern the access and use by the User of the application called "Waveful" (the "Platform"), created and provided by Waveful S.r.l., with headquarters in Italy, 20121 Milan (MI), Via Daniele Manin 3, VAT Identification Number IT12343330960, e-mail for communications termsofuse@waveful.app (the "Provider").
        The terms used with a capital letter ("Definitions") shall have the meaning set forth below:
        Account: means the IT environment made available by the Provider, including the possibility for the User to use the Services and to enter and/or modify the Data in their Profile.
        Badges: means the graphic elements that the User can use to customize his Profile.
        Consumer Code: means the Italian Legislative Decree N ° 206/2005 and subsequent amendments and additions.
        Contents: means any music, sound element, photograph, image, video, message, or other material, uploaded and/or published by the User on the Platform (by way of example, posts, comments, messages sent and/or received through the Messaging Service, etc.).
        Creator: indicates a particular category of User who will be entitled to monetize through the engagement generated by the Contents uploaded and/or published on the Platform based on the specific terms and conditions reserved for them.
        Data: indicates any information relating to the User, such as, but not limited to, name, photo and bio.
        Followers: means Users who decide to follow a User, thus being able to access the available Contents and Data of the latter.
        Invite Friends: means the function through which a User can invite a person to register on the Platform by sharing a specific link in a section of the Profile. In the event that the invited person signs up on the Platform, the User will receive some benefits (by way of example: (i) activation of the Premium Service for 7 days, with the exception of superlikes; (ii) special Badges based on the number of new Users who have registered by sharing the link indicated above).
        Messaging Service: means a private chat service through which the User can exchange messages with another User.
        OAuth Services: means the online authentication services developed on OAuth and/or similar protocols, through which the User is able to create an Account importing some Data from an existing account on third-party platforms (e.g. Google and/or Apple).
        Rights: indicate any and all rights deriving from a patent, trademark, utility model, design, copyright or other industrial and/or intellectual property right, including the right to his/her own name, personal image and confidentiality of his/her own personal data, honor, reputation, decorum, as well as commercial reputation.
        Rights on the Waveful Software: indicate all the Rights concerning the Waveful Software, expressly including the exclusive rights provided for by the law of 22 April 1941, n. 633 and subsequent amendments and additions and, in particular, by articles 64-bis and following of the same law. By way of example only and, therefore, without any claim of completeness, the following rights fall within the Rights on the Waveful Software: reproduction, execution, loading, processing, adaptation, translation, distribution, dissemination to the public, distribution of elaborated and/or modified and/or adapted versions.
        Parties: mean the Provider and the User.
        Platform: means the computer program underlying the Services, including the functional and graphic interfaces, exclusively owned by the Provider and on which the Provider holds all the Rights. The User can use the Platform by downloading the mobile application created for the iOS and/or Android operating systems ("Application").
        Premium Service: means the paid service through which the User can use all the features of the Platform without advertisements, as well as receive a certain number of Superlikes to be used on the Platform.
        Profile: indicates a page of the Platform in which the User can share certain Data (by way of example, name, photo, bio) and/or Contents.
        Registration: means the procedure where a specific natural person, after downloading the Application, shall enter some Data (also through the OAuth Service) and on successful sign up, will be enabled to access and use the Services offered by the Provider through the Platform, in compliance with these Conditions.
        Services: indicate all the features that the Provider provides to Users of the Platform and include, by way of example: i) access and use of the Platform; ii) the Premium Service; iii) the Messaging Service; iv) OAuth services.
        Island: indicates an area of the Platform where the User can publish and/or view only Contents belonging to a single thematic area (e.g. news, gaming etc.).
        User: means the subject, a natural person, who uses the Platform and registers with it in order to use the Services in compliance with these Conditions. Users are informed that it is strictly forbidden to register on the Platform without fulfilling with the age requirements provided for by the legislation of their country (by way of mere example, Italian users are allowed to sign up from the age of fourteen).
        Waveful Software: means the set of instructions, classes, codes, libraries, objects, functions, diagrams, style sheets, icons, functional and/or graphic interfaces, placed at the base of the Services and, in particular, of the Platform and/or the Waveful database.
        Art. 1 - Recitals and Definitions
        1.1. The Recitals and Definitions form an integral and essential part of these Conditions.

        1.2. The Recitals and Definitions form an integral and essential part of these Conditions.The Definitions indicated in these Conditions shall have the same meaning (except for the number) if used in the plural and vice versa.

        Art. 2 - Modification of the Conditions
        2.1. The Provider reserves the right to update and modify these Conditions at any time, at its sole discretion and, in any case, in the event that updates and modifications are necessary in order to comply with legislative or regulatory changes or in order to introduce additional security measures relating to the Platform.

        2.2. The Provider also expressly undertakes to publish the updated version of the Conditions on the Platform. Updates and changes will be notified to Users by a pop-up alert at the next login to the Platform or by e-mail to the address indicated by the User during registration.

        2.3. It is expressly understood that the changes and/or updates will have retroactive effect only in the event that such retroactive effect is required by legislative measures and/or by administrative, governmental or judicial bodies or authorities. In any other case, the updates and changes shall be considered as tacitly accepted by the User unless the latter sends a written communication to the Provider - in the manner that will be indicated by the Provider and in any case within the following 30 days - by which he declares to not to accept the updates and changes in question and to withdraw from the contractual relationship between the Parties.

        Art. 3 - Conditions of access to the Platform
        3.1. The Provider will allow the User to access to the Platform under the conditions and within the limits deriving from this Agreement.

        3.2. In order to use the Platform, the User must:

        download the Application;
        complete the Registration procedure (e.g. the User will have to enter the required Data, even through the use of the OAuth Services);
        promptly and constantly update his/her Data so that they are always up-to-date, complete and truthful;
        not to use third party accounts.
        3.3. The User declares and warrants under his own responsibility that he fulfils with the age requirements provided for by the legislation of his country.

        3.4. The Provider reserves the right to periodically verify and check the accuracy of the User Data and, in the case of proven irregularities and/or inaccuracies (including those relating to the fulfilment with the age requirements referred to in the previous art. 3.3), also reserves the right to withdraw from this Agreement without notice. As a consequence, the latter’s access to the Platform shall be disabled, with the exclusion of any and all rights to reimbursements, indemnities and/or damages, direct and indirect, material and non-material, potential, current, future, punitive (by way of example and not limited to: damages for loss of profits, goodwill).

        3.5. The Parties, with regard to the effective date of the Agreement, acknowledge and agree that the provision by the Provider of the Services to User is subject to the completion of the Registration procedure.

        Art. 4 - User Obligations
        4.1. The User undertakes to access the Platform in full compliance with the laws in force and, in any case, undertakes not to carry out the following actions:

        download the Application; upload, publish, share, in any way or form, through the Platform, illicit, illegal or prohibited Contents, or Contents associated with any type of illegal, illegal or prohibited Contents;
        upload, publish, share Content containing obscene, blasphemous, pornographic, racist, denigrating, discriminatory, defamatory language or which, in any case, may harm the honour and/or reputation of the Provider, other Users and/or of third parties, natural and/or legal persons;
        upload, publish, share Content or carry out activities that sexually exploit, abuse, or endanger children (this includes, for example, grooming a child for sexual exploitation, sextorting a child, trafficking of a child for sex, or otherwise sexually exploiting a child); We are committed to child safety and when we become aware of apparent child exploitation, we report it to the relevant authorities, in compliance with applicable law;
        upload and/or publish Contents for which it is not the exclusive owner of the Rights;
        violate any third party Right. In particular, in the event that the uploaded and/or published Contents contains personal data of third parties, the User declares and guarantees to act in compliance with the privacy legislation in force;
        upload, publish, share, in any way or form, through the Platform, Contents and/or material intended for the commission of illegal activities, including, by way of example and not limited to, incitement to violence and/or the commission of crimes of any kind;
        transmit viruses and/or other IT tools that may compromise the integrity and/or security of the Platform and/or IT equipment (so-called malware, trojan horses, etc.);
        carry out activities related to spamming and/or any type of unwanted interaction with other Users;
        report and/or disseminate links to websites where one of the prohibited activities indicated above is carried out.
        4.2. The User who creates an Island will acquire the status of administrator and will therefore have the right to: (i) appoint other Users as administrators; (ii) remove Contents that does not comply with the Island theme (e.g. sports content published in an Island related to music); (iii) temporarily suspend a User's access to the Island in cases of serious violation of the guidelines.

        Art. 5 - Intellectual property and licenses
        5.1. The User acknowledges that all the Rights on the Platform, on the Services and on the Waveful Software, together with those relating to graphic motifs, interfaces, as well as any distinctive signs are the exclusive property of the Provider and that the User expressly undertakes to not to reproduce them, modify them, alter them, remove them, move them, sell them, license them and/or distribute them to third parties.

        5.2. Subject to compliance with these Conditions, the Provider grants the User a personal, non-exclusive (the Provider may also grant the license to other Users) and non-transferable (the licensed User may not assign the rights provided for in this license) license concerning the use of the Platform for the sole purpose of accessing the Services.
        Users are informed that the license is free, with the exception of the Premium Service, the Superlikes and the Special Colors, whose license to use is subject to a fee according to the economic conditions applicable from time to time and made available on the Application

        5.3. Without prejudice to what is specified above in art. 5.2, the Provider reserves all Rights not expressly granted with this license.
        By way of mere example, therefore, the User cannot, either directly or indirectly:

        distribute, license, sublicense, rent, lease, sell or transfer, in whole or in part, the Platform and/or the Waveful Software;
        reverse engineer, decompile, disassemble or attempt to discover, in whole or in part, the source code and object code underlying the Platform and/or the Waveful Software;
        modify, alter or create derivative works, in whole or in part, from the Platform and/or the Waveful Software;
        remove, alter or obscure copyrights, trademarks or other elements relating to Rights connected with the Platform and/or with the Waveful Software and/or with any other material given to the User by Waveful;
        use third-party software to modify the Platform and/or the Waveful Software, its methods of use or the Services;
        redirect, intercept or emulate any communication protocol used by the Provider as part of the Services offered through the Platform by any means, such as, but not limited to, protocol emulation, reverse engineering, packet sniffing, or modification or addition of components to the Platform and/ or the Waveful Software;
        provide, host, facilitate, connect to or use private servers, emulators, "matchmaking" services or other means that allow the Platform and/or the Waveful Software to be used outside the Services;
        create, use or maintain unauthorized links to the Platform, the Waveful Software and/or the Services.
        5.4. The User may not distribute and/or provide to third parties, publish on websites, and/or perform and/or exhibit in public any part of the Platform, the Waveful Software and/or the Services, without the prior written authorization of the Provider.

        5.5. Without prejudice to the application of the mandatory rules on personal data, the User grants the Provider a license relating to the Contents and Data uploaded and/or published by the same User. The license is free (the User will not receive any consideration, with the exception of the Creator to whom specific terms and conditions will apply), non-exclusive (the User may license the Content and Data uploaded and/or published also to third parties), worldwide, transferable (the Provider may assign the rights under this license), sublicensable (the Provider may in turn license the Contents and User Data to thirdparties). The Provider, therefore, may use, in any way and/or form (by way of example through modification, processing, translation, adaptation, distribution, etc.) the Contents and Data uploaded and/or published by the User for promotional purposes (e.g. on their social channels). The license shall be granted for an indefinite period, without prejudice to the User's right to delete specific Contents and/or Data or right of withdrawal. In these cases, however, the Provider shall not delete the Contents that have been reprocessed by other Users (see license art. 5.6) and/or the Contents and/or Data that the Provider may use in accordance with the provisions of art. 135 noviesdecies, paragraph 4, of the Consumer Code (by way of example only, the number of likes and/or Superlikes used by the User, the number of Contents published, etc.).

        5.6. The User grants other Users a license relating to the Contents and Data uploaded and/ or published by the same User. The license is perpetual, free (the User will not receive any consideration), non-exclusive (the licensing User may license the Contents and Data uploaded and/or published also to third parties), worldwide, transferable (licensed Users may assign the rights provided for in this license), sublicensable (licensed Users may in turn license the Contents and User Data to third parties). Users, therefore, may use, in any way and/or form (by way of example through modification, processing, translation, adaptation, distribution, etc.) the Contents and Data uploaded and/or published by the User for any and all purposes. This license, therefore, will allow Users to re-share the Contents of other Users on their own profile and/or on Islands.

        5.7. Users are informed that in the event that the User creates Contents through the Platform (e.g. using the "photo" feature or modifying Contents uploaded from their device and modified through the Platform features), such Contents may be downloaded and saved by the User on their device, but they may contain the Provider's trademark or any other distinctive sign, as well as the User's username.

        Art. 6 - Disclaimer of warranties, exclusions and limitations of liability
        6.1. The Platform, released in the most recent version available at the time of installation or updates, is provided without a guarantee of operation (so-called "as it is"), with respect to all possible applications and uses.

        6.2. Without prejudice to the application of any mandatory provisions of law, the Provider does not provide and does not recognize any guarantee for original or supervening defects, does not make any promises of quality, proper operation or suitability for a particular purpose or result in relation to the Platform and does not guarantee that the Platform will meet the User's needs.

        6.3. Without prejudice to the application of any mandatory provisions of law, any and/or any liability of the Provider connected or in any way deriving from the use of the Platform is excluded. Consequently, any and all right to indemnity and/or compensation for damages, direct and indirect, material and non-material, potential, current, future, punitive (by way of example and not limited to: damages for loss of profits, goodwill, use, data), to people and/ or things, connected or in any way deriving from the use of the Platform, is excluded.

        6.4. The Parties acknowledge and agree that any and all relationship, interaction, connection between Users that may occur through the use of the Platform and/or through the contact tools made available by the User will take place, in any case, outside the Provider’s control. In fact, the User is informed that:

        the Provider does not control or supervise Users (including Island administrator Users) and their behaviour within the Platform;
        the Provider does not control the possible reuse, in whole or in part, of the Contents uploaded and/or published by other Users.
        Consequently, the User acknowledges and agrees that any and all liability of the Provider in this regard is expressly excluded, as well as any and all right to compensation and/or damages, direct and indirect, material and non-material, potential, current, future, punitive (by way of example and not limited to: damage for loss of profits, goodwill, use, data), to people and/or things, directly and/or indirectly attributable to interactions between Users.

        Art. 7 - Indemnity
        The User - without prejudice to the Provider's right to claim compensation for any suffered damage - declares and guarantees to indemnify and hold harmless the Provider, as well as the subjects connected to it or controlled by it, its representatives, employees, as well as any of its partner from any and all harassment, disturbance, claim, proceeding or legal action, initiated or threatened, by the competent authorities, by third parties or by Users connected or in any way deriving from the use of the Platform in breach of these Conditions, including the possible infringement of the Rights of third parties, and in particular in the event of breach of the obligations deriving from or in any case connected with articles 4, 5. The indemnity obligation shall cover any and all costs, expenses, charges (including expenses and fees for lawyers, consultants, experts etc.) arising from or in any way connected with the aforementioned circumstances.

        Art. 8 - Duration and withdrawal of the User
        8.1. The contractual relationship between the Provider and the User shall have an indefinite duration.

        8.2. However, the User is informed that he may withdraw from this Agreement at any time, without specifying the reasons and without penalty, using the automatic account deactivation procedure available within the User's Account.

        8.3. In the event that the User withdraws from this Agreement pursuant to the previous art. 8.2, the Provider will keep the User Data and Contents for a period of 30 (thirty) days from the deactivation of the Account. With the exception of the cases provided for by art. 135 noviesdecies, paragraph 5, of the Consumer Code (by way of example only, the number of likes and/or Superlikes used by the User), during this period the User has the right to ask the Provider to return the uploaded Data and Contents in a commonly used and machine-readable format. Without prejudice to the provisions of art. 5.5, the Provider undertakes to delete the User Contents and Data from its databases, as soon as possible and, in any case, no later than 30 (thirty) days after the expiry of the previous term.

        Art. 9 - Suspension of the use of the Platform
        9.1. The Provider reserves the right (also in case of User’s breach of the Agreement) to temporarily suspend, in whole or in part - even without notice in cases of necessity and urgency - with the exclusion of any return, indemnity and /or compensation, the User’s access to the Platform in the following cases:

        there are well-founded reasons to believe that unauthorized third parties are accessing to the Platform with User’s credentials;
        modifications, interventions and/or maintenance to the Platform that are necessary for security reasons or to ensure a better operation of the Platform;
        the User is involved, in any capacity, in any judicial or even extrajudicial dispute of a civil, criminal or administrative nature that derives from or is in any way connected with the use of the Platform by the User;
        disputes and/or requests from the competent authorities;
        there are well-founded reasons to believe that the User has breached any of the obligations provided for in articles 3, 4, 5.
        9.2. In any case of suspension of the use of the Platform arisen from the User’s behaviour, the Provider has the right to claim compensation for any suffered damage.

        9.3. In the event of suspension of services without notice, the Provider must in any case activate the internal conciliation system referred to in the following art. 11 within 48 (forty-eight hours) from the suspension.

        Art. 10 - Express termination clause
        In the event that the User breaches even one of the obligations deriving from articles 3, 4, 5, 7, the Provider, after activating the internal conciliation system referred to in the following art. 11, may terminate the Agreement between the Parties by sending the User a written notice stating that he wishes to enforce this clause. In the event of the enforcement of the express termination clause, the provisions of the previous articles 8.3, 8.4 shall apply.

        Art. 11 - Internal conciliation system
        11.1. When the Provider, even after the notification of another User and/or a competent authority, finds a breach of articles 3, 4, 5, 7, it must send a written notice to the User involved. This notice must contain a description of the facts disputed to the User (e.g. the provisions that are intended to be infringed and the related elements in support of the infringement). Upon receipt of the notice, the User may submit his/her written comments within the following 5 (five) days.

        11.2. After the receipt of the User’s written comments, the Provider, at its sole discretion, may, however, proceed with the application of the remedies referred to in articles 9 (in less serious cases) or 10 (in more serious cases, including the case of repeated breaches of these Conditions).

        Art. 12 - Privacy
        Personal Data collected as part of the use of the Services will be processed in accordance with the privacy policy available at the following link https://waveful.app/privacy.

        Art. 13 - Miscellaneous
        13.1. These Conditions contain in their entirety the agreements between the Parties and cancel and replace any previous agreement on the same subject. Any agreement added to or modifying what is contained herein must be formulated in writing by the Parties and signed by them.

        13.2. If a clause or part thereof is deemed null and/or void, that shall not lead to the entire Conditions or the remainder of the said clause becoming null and void or being terminated.

        13.3. This Agreement does not determine corporate or associative ties between the Parties and does not imply any relationship of representation between them, so no Party will have the right to act in the name and on behalf of the other Party.

        13.4. The User may not assign this Agreement, in whole or in part, or any of the rights deriving from it, without the prior written consent of the Provider. Any transfer that occurs without the prior written consent of the Provider will be null and void. The Provider reserves the right to transfer and/or assign this Agreement, in whole or in part (including individual rights or obligations), for any reason, as long as the User's rights provided herein are not affected.

        13.5. Any failure by the Provider to exercise the rights and powers deriving from these Conditions does not in any way constitute a waiver of the same, having to be considered as a mere act of tolerance.

        13.6. All communications provided for in this Agreement may be sent, as regards the Provider, to the e-mail address indicated in Recital a) and, as regards the User, to the e-mail address provided during the Registration procedure and/or on the internal messaging system of the Platform and/or via SMS. All communications shall take effect upon receipt. Each Party must promptly notify the other of any changes to their e-mail addresses, it being understood that, in the event of failure to rectify, the notices sent to the aforementioned e-mail addresses and/or using the additional contact methods indicated above will be considered valid and effective.

        Art. 14 - Applicable law and exclusive jurisdiction
        Except for the application of mandatory law provisions:

        this Agreement is governed by Italian law, with the exclusion of any reference to the legislation on international private law;
        for any dispute relating to the validity, existence, interpretation, application, execution and/or termination of one or more clauses of this Agreement, or in any case deriving from it in any way, the Court of Rome will have exclusive territorial jurisdiction, with the express exclusion of any alternative and/or competing forum.
        Published on January 14, 2025.
        </section>
        <Hero />
      </main>
    </>
  );
}
